Files = 
{
	"Assets/UI/TownIcon.png",
	
	"Assets/Tile/Terrain/Grassy.bmp",
	"Assets/Tile/Terrain/GrassyOld.bmp",
	"Assets/Tile/Terrain/Snowy.bmp",
	"Assets/Tile/Terrain/Dry.bmp",
	"Assets/Tile/Terrain/Rocky.bmp",
	"Assets/Tile/Terrain/UnderWater-0.bmp",
	"Assets/Tile/Terrain/UnderWater-1.bmp",
	"Assets/Tile/Terrain/UnderWater-2.bmp",
	"Assets/Tile/Terrain/UnderWater-3.bmp",
	"Assets/Tile/Terrain/Beach.bmp",
	"Assets/Tile/Terrain/Grass.bmp",
	"Assets/Tile/Terrain/Dirt.bmp",
	"Assets/Tile/Terrain/Forest.bmp",
	"Assets/Tile/Terrain/Ice.bmp",
	"Assets/Tile/Terrain/Sand.bmp",
	"Assets/Tile/Terrain/ThinIce.bmp",
	"Assets/Tile/Terrain/ThickIce.bmp",
	"Assets/Tile/Terrain/Road1.bmp",
	"Assets/Tile/Terrain/TownRoad.bmp",
	
	"Assets/Building/HouseX4Y4.bmp",
	"Assets/Building/HouseX5Y3.png",
	"Assets/Building/HouseX5Y4.png",
	
	"Assets/Tree/ColdTree.png",
	"Assets/Tree/GreenTree.png",
	"Assets/Tree/HalfSnowTree.png",
	"Assets/Tree/RainTree.png",
	"Assets/Tree/YellowTree.png",
	"Assets/Tree/DeadTree.png",
	
	"Assets/Grass/ColdGrass.png",
	"Assets/Grass/GreenGrass.png",
	"Assets/Grass/HalfSnowGrass.png",
	"Assets/Grass/RainGrass.png",
	"Assets/Grass/TallGrass.png",
	"Assets/Grass/YellowGrass.png",
	
	"Assets/Creature/Green.png",
	"Assets/Creature/Bug.png",
	"Assets/Creature/Dry.png",
	"Assets/Creature/Pink.png",
	"Assets/Creature/Snow.png",
	"Assets/Creature/Worm.png",
}